### ISSUE TITLE
Crashing when moving around notes 

### ISSUE THREAD

**Issue by hackrphreakr** [rajatkulkarni95/octarine-feedback#17] opened 2024-12-04 02:28 UTC
App crashes frequently when moving around notes or folders in the sidebar

**Comment by rajatkulkarni95** [comment] 2024-12-04 02:30
Can you send a reproducible video?

**Comment by rajatkulkarni95** [comment] 2024-12-10 02:20
Closing since no info provided, and there's no actionable steps.

Feel free to open when you can add more details in.

**Closed by rajatkulkarni95** 2024-12-10 02:20 UTC
Labels: bug, needs more info
