### ISSUE TITLE
Create a new document, and there is nothing but a blank page.

### ISSUE THREAD

**Issue by jlhulclq** [rajatkulkarni95/octarine-feedback#10] opened 2024-09-04 18:24 UTC
![截图 - 2024-9-4 18 23 48](https://github.com/user-attachments/assets/bcaa3e44-6876-4bd3-8364-588260c76532)

**Comment by rajatkulkarni95** [comment] 2024-09-04 18:26
What happens you reload? Does it happen for every new document creation? Assuming you are on v0.17.0?

**Comment by jlhulclq** [comment] 2024-09-04 18:27
Yes, I encountered this issue after updating to the latest version.

**Comment by rajatkulkarni95** [comment] 2024-09-04 18:31
Taking a look.

**Comment by jlhulclq** [comment] 2024-09-04 18:33
https://github.com/user-attachments/assets/2ba5086a-bc56-477f-9ade-b0cf6a9ed310

**Comment by rajatkulkarni95** [comment] 2024-09-04 18:35
Yep, could reproduce! Was weird that it didn't happen until now. Know where the issue is, will push a fix in some

**Comment by jlhulclq** [comment] 2024-09-04 18:36
Okay, then I will use the old version first. Thank you.

**Comment by rajatkulkarni95** [comment] 2024-09-04 18:51
Pushing a fix in some, the issue is very intermittent, since I reloaded, and restarted the app, and it no longer happens. Anyway shipping v0.17.1 in the next 20 mins that should resolve it.

**Comment by jlhulclq** [comment] 2024-09-04 18:56
Your efficiency is too high! I really like Octarine.

**Comment by rajatkulkarni95** [comment] 2024-09-04 19:10
@jlhulclq Can you download `v0.17.1` and check if the app still crashes? Tested on my machine, and it doesn't.

**Comment by rajatkulkarni95** [comment] 2024-09-04 19:17
Fixed with [v0.17.1](https://octarine.app/changelog/0.17.1)

**Closed by rajatkulkarni95** 2024-09-04 19:17 UTC
