### ISSUE TITLE
Crash after creating new note

### ISSUE THREAD

**Issue by tonilampela** [rajatkulkarni95/octarine-feedback#23] opened 2024-12-17 08:54 UTC
Octarine had complete crash when I created new note and had finished entering title for the note. I'm storing my notes on iCloud Drive. Issue is not reproducible every time, but in recent versions I've experienced crash already twice within a week when I didn't have any crashes before that for weeks.

**Desktop (please complete the following information):**
 - OS: macos 15.2
 - Version 0.20.0

**Additional context**
Crashdump attached.
[crash.log](https://github.com/user-attachments/files/18162749/crash.log)

**Comment by rajatkulkarni95** [comment] 2024-12-17 10:31
Is it possible that there's network latency or the iCloud drive is inaccessible? I think the crash happens when it tries to create/save a note, but the app has no access to the path (due to the above).

I'll take a look and try to reproduce it. I have a PR to improve error handling so that it doesn't crash the app, but rather gracefully handle the error and show it to the UI.

**Comment by rajatkulkarni95** [comment] 2024-12-18 14:05
@tonilampela Have a fix for this and other such scenarios. Details in #24. Tentative release is this weekend.

**Comment by rajatkulkarni95** [comment] 2024-12-20 02:27
This has been fixed in [0.20.1](https://octarine.app/changelog/0.20.1). However, if you still see issues, feel free to reopen this issue or create a new one

**Closed by rajatkulkarni95** 2024-12-20 02:27 UTC
Labels: bug
